workflows:
  build-android:
    name: Build Android APK (Capacitor + Vite)
    max_build_duration: 60
    environment:
      node: 18
      java: 17
    scripts:
      - name: Install dependencies
        script: |
          npm install

      - name: Run Capacitor setup (auto-generate android folder)
        script: |
          bash ./capacitor-setup.sh

      - name: Build Android APK
        script: |
          cd android
          ./gradlew assembleDebug

    artifacts:
      - android/app/build/outputs/**/*.apk