workflows:
  build-android:
    name: Build Android APK (Capacitor + Vite)
    max_build_duration: 60

    environment:
      node: 20
      java: 17

    scripts:
      - name: Install dependencies
        script: |
          npm ci

      - name: Build Vite project
        script: |
          npm run build

      - name: Capacitor Sync Android
        script: |
          npx cap sync android

      - name: Build Android APK
        script: |
          cd android
          ./gradlew assembleDebug

    artifacts:
      - android/app/build/outputs/**/*.apk