workflows:
  react-native-workflow:
    name: React Native Build
    max_build_duration: 60
    environment:
      node: 18
      android: true
      xcode: latest
    scripts:
      - npm install
      - npm run build
    artifacts:
      - build/**/*