workflows:
  react-native-workflow:
    name: React Native Build
    max_build_duration: 60
    environment:
      node: 18
      vars:
        ANDROID_HOME: /opt/android-sdk
    scripts:
      - npm install
      - npx react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res
      - cd android && ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/**/*.apk