workflows:
  build-android:
    name: Build Android Release
    max_build_duration: 60
    environment:
      node: 18
      java: 17
      android: sdk
    scripts:
      - name: Install dependencies
        script: |
          npm install
          npm install @react-native-community/cli --save-dev
      - name: Bundle JS for Android
        script: |
          npx react-native bundle \
            --platform android \
            --dev false \
            --entry-file index.js \
            --bundle-output android/app/src/main/assets/index.android.bundle \
            --assets-dest android/app/src/main/res
      - name: Build APK
        script: |
          cd android
          ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/**/*.apk