workflows:
  build-android:
    name: Build Android APK (Capacitor + Vite)
    max_build_duration: 60

    environment:
      node: 20
      vars:
        JAVA_HOME: /Library/Java/JavaVirtualMachines/zulu-17.jdk/Contents/Home
        PATH: /Library/Java/JavaVirtualMachines/zulu-17.jdk/Contents/Home/bin:$PATH

    scripts:
      - name: Use Node 20
        script: |
          echo "Using Node version:"
          node -v
          npm -v

      - name: Install dependencies
        script: |
          npm install

      - name: Build Vite project
        script: |
          npm run build

      - name: Run Capacitor sync
        script: |
          npx cap sync android